# Docker compose for frontend & backend

name: devops-jenkins

services:
  frontend:
    build:
      context: ./dist
    restart: always
    ports:
      - "80:80"

  backend:
    build:
      context: ./DevopsClassBackend
    restart: always
    environment:
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: my-user-pw
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    networks: 
      - mynetwork
    depends_on: 
      - database

  database:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: my-user-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_PORT: 3306
    networks: 
      - mynetwork

networks:
  mynetwork:
    driver: bridge