# Docker compose for frontend & backend

name: devops-jenkins

version: '3.8'

services:
  frontend:
    build:
      context: ./dist
    restart: always
    ports:
      - "80:80"

  backend:
    build:
      context: ./DevopsClassBackend
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "8000:8000"
    networks: 
      - mynetwork
    depends_on: 
      - database

  database:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    networks: 
      - mynetwork

networks:
  mynetwork:
    driver: bridge