image: docker:latest

stages:
  - build
  - test

services:
  - docker:dind

before_script:
  - export $(cat .env | xargs)
  
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - docker compose up -d
  artifacts:
    paths:
      - docker-compose.yml

test:
  stage: test
  script:
    - apk update
    - apk add --no-cache python3 py3-pip
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip install pytest selenium
    - docker compose up -d
    - sleep 15
    - python testfile.py
  artifacts:
    paths:
      - docker-compose.yml