# Docker compose for frontend & backend

name: devops_docker_example

services:
  database:
    image: mysql:latest
    restart: always
    environment: 
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    networks: 
      - mynetwork

  frontend:
    build:
      context: ./dist
    restart: always
    ports:
      - "80:80"
  
  backend:
    build:
      context: ./DevopsClass
    restart: always
    environment:
      MYSQL_DATABASE: devopsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: my-user-pw
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    ports:
      - "8000:8000"
    networks: 
      - mynetwork
    depends_on: 
      - database

networks:
  mynetwork:
    driver: bridge